[package]
name = "bevy_tilemap"
version = "0.3.1"
authors = ["Joshua J. Bouw <dev@joshuajbouw.com>"]
edition = "2018"
description = "Tilemaps with chunks for the Bevy game engine, a simple-driven game engine and app framework"
repository = "https://github.com/joshuajbouw/bevy_tilemap"
license = "MIT"
keywords = ["game", "engine", "bevy", "tiles", "tilemap"]
categories = ["game-engines", "graphics", "gui"]
readme = "README.md"
documentation = "https://docs.rs/bevy_tilemap/latest/bevy_tilemap/"
exclude = ["assets/**/*", ".github/**/*", "doc/**/*"]

[package.metadata.docs.rs]
features = ["serialize", "types"]

[features]
default = []

# crate
types = []

# serde
serialize = ["bevy_tilemap_types/serialize", "serde"]

[workspace]
members = ["library/*", "examples"]

[dependencies]
bevy_app = "0.4"
bevy_asset = "0.4"
bevy_core = "0.4"
bevy_ecs = "0.4"
bevy_log = "0.4"
bevy_math = "0.4"
bevy_rapier2d = { version = "0.7.0", optional = true }
bevy_render = "0.4"
bevy_reflect = "0.4"
bevy_sprite = "0.4"
#bevy_tilemap_core = { path = "library/core", version = "0.4" }
bevy_tilemap_types = { path = "library/types", version = "0.4" }
bevy_transform = "0.4"
bevy_utils = "0.4"
bevy_window = "0.4"
bitflags = "1.2"
hexasphere = "3.1"
serde = { version = "1.0", features = ["derive"], optional = true }
