[package]
name = "bevy_tilemap"
version = "0.2.1"
authors = ["Joshua J. Bouw <dev@joshuajbouw.com>"]
edition = "2018"
description = "Tile maps with chunks for the Bevy game engine, a simple-driven game engine and app framework"
repository = "https://github.com/joshuajbouw/bevy_tilemap"
license = "MIT"
keywords = ["game", "engine", "bevy", "tiles", "tilemap"]
categories = ["game-engines", "graphics", "gui"]
readme = "README.md"
documentation = "https://docs.rs/bevy_tilemap/latest/bevy_tilemap/"
exclude = ["assets/**/*", ".github/**/*", "doc/**/*"]

[dependencies]
bevy = { version = "0.3" }
serde = { version = "1.0", optional = true, features = ["derive"] }

[dev-dependencies]
rand = "0.7"

[[example]]
name = "random_dungeon"
path = "examples/random_dungeon.rs"