name: Windows-2019

on:
  push:
    branches: [ master, bevy_nightly ]
  pull_request:
    branches: [master, bevy_nightly]

jobs:
  check:
    name: Check
    runs-on: windows-2019
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.43.0 # MSRV
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
