on:
  pull_request:
    branches: [master, bevy_nightly]

name: Windows-2019

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly
          - 1.43.0 # MSRV
    runs-on: Windows
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
